### ISSUE TITLE
app colors 정의

### ISSUE THREAD

**Issue by NOGUEN** [NewFit/NewFit-App#3]
## Background
app colors 정의

## Todo
- [x] app color blue
- [x] app color sky 
- [x] app color newfit
